// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeG6C-xyqPZjsUU7xrlJweObnEsQVXUBU',
    appId: '1:483649040994:web:c96c419f1b7fd7f56a173b',
    messagingSenderId: '483649040994',
    projectId: 'todo-project-e08d7',
    authDomain: 'todo-project-e08d7.firebaseapp.com',
    storageBucket: 'todo-project-e08d7.appspot.com',
    measurementId: 'G-DWH77XW1VB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgX5D6Hd8SAa0KsctGekWgy2NsTsm2CuE',
    appId: '1:483649040994:android:d74d36adc9bde52d6a173b',
    messagingSenderId: '483649040994',
    projectId: 'todo-project-e08d7',
    storageBucket: 'todo-project-e08d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxNrMvExrjG--Tx0AYk7hGyAEpVuQdafc',
    appId: '1:483649040994:ios:5b428d2ae58b67bf6a173b',
    messagingSenderId: '483649040994',
    projectId: 'todo-project-e08d7',
    storageBucket: 'todo-project-e08d7.appspot.com',
    iosBundleId: 'com.example.todoRoute',
  );
}
